[package]
name = "ap_cover"
version = "0.1.0"
edition = "2021"

[lib]
name = "ap_cover"
path = "src/lib.rs"

[[bin]]
name = "ap_cover"
path = "src/main.rs"

[dependencies]
rug = { version = "1.27", default-features = false, features = ["integer"] }
gmp-mpfr-sys = { version = "1.6", default-features = false, features = ["use-system-libs"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
